### 29 June 2026

Core python - last topic -> numpy

- Python library used for numerical computations
- faster than list -> array > list
- more storage efficient

- -> numpy is a python library for numerical computing that provides fast and memeory-efficient arrays.
Compared to python lists, numpy array store same - type elements( in list we can store different data type) and perform mathematical operations faster.

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
np.zeros(5)  # function -> gives zeroes and ones only

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(5,7)           # first index -> no of elements and second index ->value

array([7, 7, 7, 7, 7])

In [ ]:
np.full((5,7),2)      # i-no of rows , j- no of columns , 2 - value

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [7]:
np.arange(1,11,2) # starting index , last index , difference

array([1, 3, 5, 7, 9])

In [8]:
np.random.rand(3,3)  #random matrix within the range of 0 and 1

array([[0.65433993, 0.17102591, 0.38056522],
       [0.25509174, 0.13314202, 0.4758002 ],
       [0.52981709, 0.05026559, 0.52737309]])

In [10]:
np.eye(3)  # identity matrix of size 3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.randint(10,50,size=(3,3)) #random matrix within the range of 10 and 50   ->dtype=int32

array([[11, 13, 45],
       [41, 23, 45],
       [40, 20, 10]])

In [13]:
np.array([[1,2,3],[4,5,6]]) #2d array

array([[1, 2, 3],
       [4, 5, 6]])

#### Array properties